[package]
name = "sizeprobe"
version = "0.1.0"
edition = "2021"

[features]
default = []
html = ["dep:html5gum"]
h5e = ["dep:html5ever", "dep:markup5ever_rcdom"]
net = ["dep:ureq"]
net-native-tls = ["net", "ureq/native-tls"]
net-rustls = ["net", "ureq/rustls"]
js = ["dep:rquickjs"]
servo = ["h5e", "dep:markup5ever", "dep:selectors", "dep:cssparser", "dep:precomputed-hash"]

[dependencies]
html5gum = { version = "0.8", optional = true }
ureq = { version = "3", optional = true, default-features = false }
rquickjs = { version = "0.12", optional = true }
html5ever = { version = "0.39", optional = true }
markup5ever = { version = "0.39", optional = true }
selectors = { version = "0.26", optional = true }
cssparser = { version = "0.34", optional = true }
markup5ever_rcdom = { version = "0.39", optional = true }
precomputed-hash = { version = "0.1", optional = true }

[profile.release]
strip = true

[profile.tiny]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = true

[profile.tiny-abort]
inherits = "tiny"
panic = "abort"
