[package]
name = "webdriver"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
base64 = "0.23"
browser = { workspace = true }
http = "1"
serde_json = "1"
server = { workspace = true }
tokio = { version = "1.53", default-features = false, features = ["sync"] }
url = "2"
