import { chromium } from "playwright";
import { spawn } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const MDN_FORM_URL = "https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/form";
const output = process.env.MDN_SCREENSHOT ?? "/tmp/tinybrowser-mdn-filled.png";
const binary = process.env.TINYBROWSER_BIN;

if (!binary) throw new Error("TINYBROWSER_BIN must name a built tinybrowser binary");

async function openCdpSocket(url) {
  const socket = new WebSocket(url);
  await new Promise((resolve, reject) => {
    socket.addEventListener("open", resolve, { once: true });
    socket.addEventListener("error", reject, { once: true });
  });
  let nextId = 0;
  const pending = new Map();
  socket.addEventListener("message", event => {
    const message = JSON.parse(event.data);
    const waiter = pending.get(message.id);
    if (!waiter) return;
    pending.delete(message.id);
    if (message.error) waiter.reject(new Error(message.error.message));
    else waiter.resolve(message.result);
  });
  return {
    send(method, params = {}) {
      const id = ++nextId;
      socket.send(JSON.stringify({ id, method, params }));
      return new Promise((resolve, reject) => pending.set(id, { resolve, reject }));
    },
    close() { socket.close(); },
  };
}

function remoteValue(reply) {
  return reply.result?.value;
}

const root = mkdtempSync(join(tmpdir(), "tinybrowser-mdn-"));
const runtime = join(root, "run");
const data = join(root, "data");
mkdirSync(runtime, { recursive: true });
mkdirSync(data, { recursive: true });
const daemon = spawn(binary, ["daemon", "--profile=mdn-form"], {
  env: { ...process.env, XDG_RUNTIME_DIR: runtime, XDG_DATA_HOME: data },
  stdio: "inherit",
  detached: true,
});

let browser;
let cdp;
try {
  const daemonJson = join(runtime, "tinybrowser", "mdn-form", "daemon.json");
  const deadline = Date.now() + 10_000;
  let port;
  while (Date.now() < deadline) {
    try {
      port = JSON.parse(readFileSync(daemonJson, "utf8")).port;
      break;
    } catch {
      await new Promise(resolve => setTimeout(resolve, 20));
    }
  }
  if (!port) throw new Error(`daemon did not publish ${daemonJson}`);

  browser = await chromium.connectOverCDP(`http://127.0.0.1:${port}`);
  const page = browser.contexts()[0].pages()[0];
  await page.goto(MDN_FORM_URL, { waitUntil: "load", timeout: 60_000 });
  await page.waitForFunction(() => {
    const example = document.querySelector("interactive-example");
    const runner = example?.shadowRoot?.querySelector("mdn-play-runner");
    return runner?.code?.html?.includes('id="name"') &&
      runner.shadowRoot?.querySelector("iframe")?.isConnected;
  }, undefined, { timeout: 30_000 });

  const code = await page.evaluate(() => {
    const example = document.querySelector("interactive-example");
    return example.shadowRoot.querySelector("mdn-play-runner").code;
  });
  const targets = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  cdp = await openCdpSocket(targets[0].webSocketDebuggerUrl);
  const tree = await cdp.send("Page.getFrameTree");
  const childFrameId = `${tree.frameTree.frame.id}.1`;

  const existing = await cdp.send("Runtime.evaluate", {
    frameId: childFrameId,
    expression: "document.querySelector('input#name') !== null",
  });
  if (!remoteValue(existing)) {
    // mdnplay.dev can be unavailable independently of MDN. The exact source
    // generated by MDN is already in the runner component, so install that
    // source into the real child browsing context rather than substituting a
    // local fixture.
    const html = `<!doctype html><style>${code.css}</style>${code.html}`;
    await cdp.send("Runtime.evaluate", {
      frameId: childFrameId,
      expression: `document.open(); document.write(${JSON.stringify(html)}); document.close()`,
    });
  }

  const filled = await cdp.send("Runtime.evaluate", {
    frameId: childFrameId,
    expression: `(() => {
      const input = document.querySelector('input#name');
      if (!input) throw new Error('MDN form input did not materialize');
      input.value = 'Tiny Browser';
      input.dispatchEvent(new Event('input', { bubbles: true }));
      input.dispatchEvent(new Event('change', { bubbles: true }));
      return input.value;
    })()`,
  });
  if (remoteValue(filled) !== "Tiny Browser") {
    throw new Error("MDN form value did not stick");
  }

  const screenshot = await cdp.send("Page.captureScreenshot", {
    format: "png",
    frameId: childFrameId,
  });
  writeFileSync(output, Buffer.from(screenshot.data, "base64"));
  console.log(output);
} finally {
  cdp?.close();
  await browser?.close().catch(() => {});
  if (daemon.pid !== undefined) {
    try { process.kill(-daemon.pid, "SIGKILL"); } catch {}
  }
  rmSync(root, { recursive: true, force: true });
}
